# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmSlice(object):
    def setupUi(self, frmSlice):
        frmSlice.setObjectName("frmSlice")
        frmSlice.resize(379, 126)
        self.spinSections = QtWidgets.QSpinBox(frmSlice)
        self.spinSections.setGeometry(QtCore.QRect(70, 10, 91, 22))
        self.spinSections.setProperty("value", 1)
        self.spinSections.setObjectName("spinSections")
        self.spinAngel = QtWidgets.QDoubleSpinBox(frmSlice)
        self.spinAngel.setGeometry(QtCore.QRect(70, 40, 91, 22))
        self.spinAngel.setObjectName("spinAngel")
        self.label_2 = QtWidgets.QLabel(frmSlice)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(frmSlice)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 49, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(frmSlice)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 49, 16))
        self.label_3.setObjectName("label_3")
        self.spinAxisX = QtWidgets.QDoubleSpinBox(frmSlice)
        self.spinAxisX.setGeometry(QtCore.QRect(60, 90, 51, 22))
        self.spinAxisX.setObjectName("spinAxisX")
        self.spinAxisY = QtWidgets.QDoubleSpinBox(frmSlice)
        self.spinAxisY.setGeometry(QtCore.QRect(110, 90, 51, 22))
        self.spinAxisY.setObjectName("spinAxisY")
        self.spinAxisZ = QtWidgets.QDoubleSpinBox(frmSlice)
        self.spinAxisZ.setGeometry(QtCore.QRect(160, 90, 51, 22))
        self.spinAxisZ.setProperty("value", 1.0)
        self.spinAxisZ.setObjectName("spinAxisZ")
        self.label_5 = QtWidgets.QLabel(frmSlice)
        self.label_5.setGeometry(QtCore.QRect(70, 70, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(frmSlice)
        self.label_6.setGeometry(QtCore.QRect(120, 70, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(frmSlice)
        self.label_7.setGeometry(QtCore.QRect(170, 70, 21, 16))
        self.label_7.setObjectName("label_7")
        self.buttonBox = QtWidgets.QDialogButtonBox(frmSlice)
        self.buttonBox.setGeometry(QtCore.QRect(220, 90, 156, 24))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(frmSlice)
        QtCore.QMetaObject.connectSlotsByName(frmSlice)

    def retranslateUi(self, frmSlice):
        _translate = QtCore.QCoreApplication.translate
        frmSlice.setWindowTitle(_translate("frmSlice", "Slice Object"))
        self.label_2.setText(_translate("frmSlice", "Angel"))
        self.label_4.setText(_translate("frmSlice", "Sections"))
        self.label_3.setText(_translate("frmSlice", "Axis"))
        self.label_5.setText(_translate("frmSlice", "X"))
        self.label_6.setText(_translate("frmSlice", "Y"))
        self.label_7.setText(_translate("frmSlice", "Z"))
