# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waitforok.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaitForOK(object):
    def setupUi(self, WaitForOK):
        WaitForOK.setObjectName("WaitForOK")
        WaitForOK.resize(77, 49)
        WaitForOK.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox = QtWidgets.QCheckBox(WaitForOK)
        self.checkBox.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(WaitForOK)
        QtCore.QMetaObject.connectSlotsByName(WaitForOK)

    def retranslateUi(self, WaitForOK):
        _translate = QtCore.QCoreApplication.translate
        WaitForOK.setWindowTitle(_translate("WaitForOK", "Dialog"))
        WaitForOK.setToolTip(_translate("WaitForOK", "Exit Mode"))
        self.checkBox.setToolTip(_translate("WaitForOK", "<html><head/><body><p>Exit Mode</p></body></html>"))
        self.checkBox.setText(_translate("WaitForOK", "OK"))
