# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(374, 200)
        frmMain.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Europe))
        frmMain.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(frmMain)
        self.buttonBox.setGeometry(QtCore.QRect(30, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(frmMain)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 161, 80))
        self.groupBox.setObjectName("groupBox")
        self.radOneFace = QtWidgets.QRadioButton(self.groupBox)
        self.radOneFace.setGeometry(QtCore.QRect(20, 20, 89, 20))
        self.radOneFace.setObjectName("radOneFace")
        self.radAll = QtWidgets.QRadioButton(self.groupBox)
        self.radAll.setGeometry(QtCore.QRect(20, 50, 89, 20))
        self.radAll.setObjectName("radAll")
        self.inpSegments = QtWidgets.QSpinBox(frmMain)
        self.inpSegments.setGeometry(QtCore.QRect(210, 60, 121, 22))
        self.inpSegments.setObjectName("inpSegments")
        self.label = QtWidgets.QLabel(frmMain)
        self.label.setGeometry(QtCore.QRect(210, 40, 91, 16))
        self.label.setObjectName("label")

        self.retranslateUi(frmMain)
        self.buttonBox.accepted.connect(frmMain.accept)
        self.buttonBox.rejected.connect(frmMain.reject)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        frmMain.setWindowTitle(_translate("frmMain", "Select Face and Segments size"))
        self.groupBox.setTitle(_translate("frmMain", "One or all faces"))
        self.radOneFace.setText(_translate("frmMain", "Only selected face"))
        self.radAll.setText(_translate("frmMain", "All faces"))
        self.label.setText(_translate("frmMain", "Segments"))
