# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgSelectObject(object):
    def setupUi(self, dlgSelectObject):
        dlgSelectObject.setObjectName("dlgSelectObject")
        dlgSelectObject.resize(325, 322)
        font = QtGui.QFont()
        font.setFamily("Guttman-Aharoni")
        font.setBold(True)
        dlgSelectObject.setFont(font)
        dlgSelectObject.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Europe))
        self.radSelectType = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType.setGeometry(QtCore.QRect(20, 60, 89, 20))
        self.radSelectType.setObjectName("radSelectType")
        self.radSelectType_2 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_2.setGeometry(QtCore.QRect(20, 80, 121, 20))
        self.radSelectType_2.setObjectName("radSelectType_2")
        self.radSelectType_3 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_3.setGeometry(QtCore.QRect(20, 100, 121, 20))
        self.radSelectType_3.setObjectName("radSelectType_3")
        self.radSelectType_4 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_4.setGeometry(QtCore.QRect(20, 120, 151, 20))
        self.radSelectType_4.setObjectName("radSelectType_4")
        self.radSelectType_5 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_5.setGeometry(QtCore.QRect(20, 140, 191, 20))
        self.radSelectType_5.setObjectName("radSelectType_5")
        self.radSelectType_6 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_6.setGeometry(QtCore.QRect(20, 160, 201, 20))
        self.radSelectType_6.setObjectName("radSelectType_6")
        self.radSelectType_7 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_7.setGeometry(QtCore.QRect(20, 180, 241, 20))
        self.radSelectType_7.setObjectName("radSelectType_7")
        self.radSelectType_8 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_8.setGeometry(QtCore.QRect(20, 200, 181, 20))
        self.radSelectType_8.setObjectName("radSelectType_8")
        self.radSelectType_9 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_9.setGeometry(QtCore.QRect(20, 220, 181, 20))
        self.radSelectType_9.setObjectName("radSelectType_9")
        self.radSelectType_10 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_10.setGeometry(QtCore.QRect(20, 240, 181, 20))
        self.radSelectType_10.setObjectName("radSelectType_10")
        self.radSelectType_11 = QtWidgets.QRadioButton(dlgSelectObject)
        self.radSelectType_11.setGeometry(QtCore.QRect(20, 260, 181, 20))
        self.radSelectType_11.setObjectName("radSelectType_11")
        self.label = QtWidgets.QLabel(dlgSelectObject)
        self.label.setGeometry(QtCore.QRect(20, 10, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Europe))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgSelectObject)
        self.buttonBox.setGeometry(QtCore.QRect(150, 290, 156, 24))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(dlgSelectObject)
        QtCore.QMetaObject.connectSlotsByName(dlgSelectObject)

    def retranslateUi(self, dlgSelectObject):
        _translate = QtCore.QCoreApplication.translate
        dlgSelectObject.setWindowTitle(_translate("dlgSelectObject", "Dialog"))
        self.radSelectType.setText(_translate("dlgSelectObject", "All Faces"))
        self.radSelectType_2.setText(_translate("dlgSelectObject", "Horizental Faces"))
        self.radSelectType_3.setText(_translate("dlgSelectObject", "Vertical Faces"))
        self.radSelectType_4.setText(_translate("dlgSelectObject", "All Edges in the Object"))
        self.radSelectType_5.setText(_translate("dlgSelectObject", "All Edges in the Face"))
        self.radSelectType_6.setText(_translate("dlgSelectObject", "All Edges in the Face"))
        self.radSelectType_7.setText(_translate("dlgSelectObject", "All Edges Horizental Direction"))
        self.radSelectType_8.setText(_translate("dlgSelectObject", "All Edges Vertical Direction"))
        self.radSelectType_9.setText(_translate("dlgSelectObject", "All Vertexes in the Object"))
        self.radSelectType_10.setText(_translate("dlgSelectObject", "All Vertexes in the Face"))
        self.radSelectType_11.setText(_translate("dlgSelectObject", "All Vertexes in the Edge"))
        self.label.setText(_translate("dlgSelectObject", "Select Desired subobjects by\n"
" selecting below options"))
