# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgSelectObject(object):
    def setupUi(self, dlgSelectObject):
        dlgSelectObject.setObjectName("dlgSelectObject")
        dlgSelectObject.resize(366, 445)
        dlgSelectObject.setMinimumSize(QtCore.QSize(0, 322))
        font = QtGui.QFont()
        font.setFamily("Guttman-Aharoni")
        font.setBold(True)
        dlgSelectObject.setFont(font)
        dlgSelectObject.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Europe))
        self.scrollArea = QtWidgets.QScrollArea(dlgSelectObject)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 331, 411))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 329, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.splitter = QtWidgets.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setGeometry(QtCore.QRect(10, 90, 311, 299))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.radSelectType = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType.setObjectName("radSelectType")
        self.radSelectType_2 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_2.setObjectName("radSelectType_2")
        self.radSelectType_3 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_3.setObjectName("radSelectType_3")
        self.radSelectType_4 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_4.setObjectName("radSelectType_4")
        self.radSelectType_5 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_5.setObjectName("radSelectType_5")
        self.radSelectType_6 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_6.setObjectName("radSelectType_6")
        self.radSelectType_7 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_7.setObjectName("radSelectType_7")
        self.radSelectType_8 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_8.setObjectName("radSelectType_8")
        self.radSelectType_9 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_9.setObjectName("radSelectType_9")
        self.radSelectType_10 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_10.setObjectName("radSelectType_10")
        self.radSelectType_11 = QtWidgets.QRadioButton(self.splitter)
        self.radSelectType_11.setObjectName("radSelectType_11")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.splitter)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(10, 10, 311, 127))
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Europe))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(dlgSelectObject)
        QtCore.QMetaObject.connectSlotsByName(dlgSelectObject)

    def retranslateUi(self, dlgSelectObject):
        _translate = QtCore.QCoreApplication.translate
        dlgSelectObject.setWindowTitle(_translate("dlgSelectObject", "Dialog"))
        self.radSelectType.setText(_translate("dlgSelectObject", "All Faces"))
        self.radSelectType_2.setText(_translate("dlgSelectObject", "Horizental Faces"))
        self.radSelectType_3.setText(_translate("dlgSelectObject", "Vertical Faces"))
        self.radSelectType_4.setText(_translate("dlgSelectObject", "All Edges in the Object"))
        self.radSelectType_5.setText(_translate("dlgSelectObject", "All Edges in the Face"))
        self.radSelectType_6.setText(_translate("dlgSelectObject", "All Edges in the Face"))
        self.radSelectType_7.setText(_translate("dlgSelectObject", "All Edges Horizental Direction"))
        self.radSelectType_8.setText(_translate("dlgSelectObject", "All Edges Vertical Direction"))
        self.radSelectType_9.setText(_translate("dlgSelectObject", "All Vertexes in the Object"))
        self.radSelectType_10.setText(_translate("dlgSelectObject", "All Vertexes in the Face"))
        self.radSelectType_11.setText(_translate("dlgSelectObject", "All Vertexes in the Edge"))
        self.label.setText(_translate("dlgSelectObject", "Select Desired subobjects by\n"
" selecting below options"))
